### ISSUE TITLE
Unescaped apostrophes at start of line

### ISSUE THREAD

**Issue by jwilk** [cpuguy83/go-md2man#110]
```console
$ cat test.md 
'foo'
'bar'
$ go-md2man < test.md
.nh

.PP
\&'foo'
'bar'
```
The converter correctly inserted `\&` before `'foo'`.
But `'bar'` needs the `\&` treatment too.

**Comment by cpuguy83** [comment]
Is this what you are looking for?

```roff
.nh

.PP
\&'foo'
\&'bar'
```

**Comment by cpuguy83** [comment]
I think https://github.com/cpuguy83/go-md2man/pull/112 should fix this.
