### ISSUE TITLE
Curly braces not escaped

### ISSUE THREAD

**Issue by asazernik** [cpuguy83/go-md2man#13]
On my shiny Ubuntu machine with a docker 1.6 install, `man docker inspect` reads as follows:

```
Getting the IP address of a container instance
       To get the IP address of a container use:

              # docker inspect --format='.NetworkSettings.IPAddress' 1eb5fabf5a03
              172.17.0.2
```

For comparison, [here](https://github.com/docker/docker/blob/7c8fca2ddb58c8d2c4fb4df31c242886df7dd257/docs/man/docker-inspect.1.md#getting-the-ip-address-of-a-container-instance) is the markdown source that generated that; note the curly braces in the original.

**Comment by cpuguy83** [comment]
Pushed up a fix, would be great if this can be tested with the existing docker man docs.

**Comment by asazernik** [comment]
Just reproduced this by building the existing docker man docs with their preferred version of go-md2man (v1.0.1). Tried building off of master (by removing the '-b v1.0.1' from their Dockerfile's git clone) but got the following errors:

```
# github.com/cpuguy83/go-md2man
./roff.go:15: cannot use roffRenderer literal (type *roffRenderer) as type blackfriday.Renderer in return argument:
	*roffRenderer does not implement blackfriday.Renderer (missing Entity method)
./roff.go:208: undefined: Man
```

For reference, my steps to reproduce were:

```
git clone git@github.com:docker/docker.git
cd docker/man
sudo docker build -t docker/md2man .
sudo docker run -v `pwd`:/docs:rw -w /docs -i docker/md2man /docs/md2man-all.sh
man man1/docker-inspect.1
# edited ./Dockerfile to change the git clone command, re-ran the last 3 commands
```

**Comment by cpuguy83** [comment]
wow, no idea how this built for me.
Fixed that compile issue.

**Comment by asazernik** [comment]
:+1:

**Comment by asazernik** [comment]
Works.

**Comment by rhatdan** [comment]
I am getting bug reports on this also, for docker inspect.  When will this get into docker?

https://bugzilla.redhat.com/show_bug.cgi?id=1240714

**Comment by asazernik** [comment]
I was planning to wait until @cpuguy83 tags a new release do the docker manbuilder can depend on it, but if this is urgent I can just go the ugly route and depend on the hash of the current master. Let me slap something together.

**Comment by rhatdan** [comment]
Well I would not say it is urgent, but I would like to see this fixed for docker-1.8, and then back port it for our docker-1.7 RHEL release.

**Comment by asazernik** [comment]
Alright. @cpuguy83 - could you tag a 1.0.3 release at the current master?

**Comment by rhatdan** [comment]
Is there a merged version?

**Comment by cpuguy83** [comment]
I wanted to test myself to make sure it's good with the docker docs but haven't had a chance.
If you say this is good I'll tag a new version!

**Comment by rhatdan** [comment]
@cpuguy83 I have not tested.  I just know what we have now is bad.  :^(

**Comment by asazernik** [comment]
Yeah, I've tested on the docker docs with master and it looks good to me (at least, curly braces come out working - I didn't run a full diff to check for other changes in behavior). If you're worried about newly-introduced bugs I can run a full diff.

(Sorry, forgot to close this when I originally confirmed the fix.)

**Comment by cpuguy83** [comment]
opened docker/docker#14808 to bump docker's checked out version.
