### ISSUE TITLE
Please make a v1.0.4 release with the latest import path change

### ISSUE THREAD

**Issue by anthonyfok** [cpuguy83/go-md2man#15]
Hello @cpuguy83,

Sorry for bothering you, but since the recent Pull Request #14 is a substantial change which changes the import path necessary to use go-md2man as a library, could you please make a v1.0.4 release to make it official and to make it easier to be packaged by various Linux distributions?

Many thanks for your help!
Anthony

**Comment by anthonyfok** [comment]
For reference, the motivation for this Issue originates from [Debian Bug#798585: golang-go-md2man-dev: v1.0.3 unusable as a library; please upgrade to snapshot](https://bugs.debian.org/798585) at https://bugs.debian.org/798585

**Comment by cpuguy83** [comment]
Sure, will push one in a few minutes.

**Comment by cpuguy83** [comment]
Done. Thanks!

**Comment by anthonyfok** [comment]
Wow, you are awesome!  Thank you very much!  :-)
