### ISSUE TITLE
Tildes disappear

### ISSUE THREAD

**Issue by rcorre** [cpuguy83/go-md2man#26]
Run `go-md2man` on the following example:

```
Tildes 1 "April 2017" go-md2man "User Manual"
==================================================

# Tildes don't work
Look at this filepath: ~/example
```

It produces the following output:

```
.TH Tildes 1 "April 2017" go\-md2man "User Manual"

.SH Tildes don't work
.PP
Look at this filepath: \~/example
```

When viewed, the tilde is replaced by a whitespace. Removing the `\` before the tilde in the output file causes the `~` to be visible.

**Comment by alkisg** [comment]
I'm affected by this too; I had to replace "~" with "$HOME" in my manpages because of this. :cry:

**Comment by alkisg** [comment]
As a temporary workaround, I put the following in my Makefile, after the go-md2man call:
```
sed 's/\\~/~/g' -i manpage
```
