### ISSUE TITLE
Lacking in Documentation

### ISSUE THREAD

**Issue by tianon** [cpuguy83/go-md2man#3]
From the [Debian bugtracker](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760486):
> ...
> the package lacks any documentation on how the input Markdown file needs
> to be formatted to get it working.
> 
> I tried the example from a similar project,
> https://raw.githubusercontent.com/sunaku/md2man/master/EXAMPLE.markdown
> but it failed completely to render that into a man page.
> 
> A simple man page for the program itself would already suffice -- iff
> written in Markdown ...

**Comment by cpuguy83** [comment]
So this is definitely an issue with my implementation.
I'm assuming for these headers it should just be bold and new-lined?

**Comment by cpuguy83** [comment]
Fixed rendering issues via #8 and added documentation here: 16d160379d14906c4707631f1987434e95f7f7b5
