### ISSUE TITLE
Prob since update to Blackfriday V2

### ISSUE THREAD

**Issue by juliengk** [cpuguy83/go-md2man#39]
This package is being used in spf13/cobra/docs to generate man pages.

It seems that since commit revision 124c15a91abbd0570c8510ba7e5a22eecfb5ba86, the following error appears.

`vendor/github.com/cpuguy83/go-md2man/md2man/roff.go:15:15: undefined: blackfriday.Extensions`

**Comment by cpuguy83** [comment]
Perhaps your blackfriday version needs to be updated?

**Comment by juliengk** [comment]
I checked and my blackfriday version is up to date. I have search for `Extensions` in blackfriday repo and could not find it https://github.com/russross/blackfriday/search?q=Extensions&unscoped_q=Extensions

**Comment by cpuguy83** [comment]
It's defined in the v2 branch: https://github.com/russross/blackfriday/blob/v2/markdown.go#L28

**Comment by juliengk** [comment]
ah cool! I only search for master branch and I have updated my version to that branch and it's working now. Sorry about that.

Thank you

**Comment by cpuguy83** [comment]
Awesome, thanks for checking!

I haven't tagged a release with the v2 changes yet just in case of breaking changes.
Let me know if there are any other issues.

Thanks!

**Comment by juliengk** [comment]
does it worth to change the import package from `github.com/russross/blackfriday` to `gopkg.in/russross/blackfriday.v2`?

**Comment by cpuguy83** [comment]
I seem to recall I was using the gopkg address at some point but it had issues or something?
In any case, this is currently using `dep` to manage deps.

**Comment by juliengk** [comment]
ok. Tanks
