### ISSUE TITLE
unable to convert html like into man page

### ISSUE THREAD

**Issue by eparis** [cpuguy83/go-md2man#4]
My md file has something like:

```
# Example

/usr/bin/kubelet --etcd_servers=http://127.0.0.1:4001
```

If I do not put anything around the example call to kubelet the man page outputs:

```
    /usr/bin/kubelet --etcd_servers= ⟨http://127.0.0.1:4001⟩
```

If I add the "triple block quote" around the line containing the link, it doesn't mess things up completely, which is good, but it instead intents the example two tabs instead of one.

```
        /usr/bin/kubelet --etcd_servers=http://127.0.0.1:4001
```

I'll live with the two tab indentation for now, but I'm not sure how to handle this...

**Comment by cpuguy83** [comment]
So, just merged a fix on master for block code.
Can you test and see if that's what you are looking for?

Or is `# Example` supposed to be a heading?
