### ISSUE TITLE
Can we get this updated for blackfriday v2 and/or get a go.mod?

### ISSUE THREAD

**Issue by pedgeio** [cpuguy83/go-md2man#43]
If you're using cobra with modules, a `go get` will end up getting blackfriday v2, which is not compatible with this library. Therefore, you have to manually push blackfriday back to v1.5.2, which is annoying if you're doing a blanket update of your deps.

Can we either:

- Update this to blackfriday v2
- Add a go.mod in this repository specifying the blackfriday v1 dependency

It would be a huge help.

Related:

https://github.com/spf13/cobra/issues/805
https://github.com/cpuguy83/go-md2man/issues/42

**Comment by cpuguy83** [comment]
This is using blackfriday v2, but I haven't cut a release for it.
This will probably necessitate a v2 release here just because it's basically a complete rewrite.

**Comment by spangenberg** [comment]
@cpuguy83 could you then please add a go.mod file in the meantime, which points to blackfriday v1.5.2?

**Comment by cpuguy83** [comment]
@spangenberg I'm curious why it is needed?

**Comment by peter-edge** [comment]
See https://github.com/spf13/cobra/issues/805 - md2man is preventing people from being able to run `go get -u ./...` for many repositories.

**Comment by cpuguy83** [comment]
What do you think about a 1.1.0 that just updates to use go mods
And then a 2.0 that will include blackfriday v2 and bump this repos mod version to /v2 as well?

**Comment by peter-edge** [comment]
Sgtm

**Comment by cpuguy83** [comment]
Created 1.0.9 which has a go.mod, but still includes vendor and `dep` related stuff just to not break people.

**Comment by cpuguy83** [comment]
And a 1.0.10 because I didn't manage to bump blackfriday to 1.5.2 on 1.0.9.

**Comment by cpuguy83** [comment]
Working on 2.0.

**Comment by chinajuanbob** [comment]
Do we have a target date for the 2.0 release?
