### ISSUE TITLE
unwanted .PP in list items

### ISSUE THREAD

**Issue by miekg** [cpuguy83/go-md2man#45]
I've got the following markdown file which has whitespace between the list items:
~~~
% more list.md
* hello1

* hello2

* hello3
~~~
converting this to nroff yields:
~~~
.RS
.IP \(bu 2

.PP
hello1
.IP \(bu 2

.PP
hello2
.IP \(bu 2

.PP
hello3

.RE
~~~
which means it is rendered with a dot and then a newline.

Is it possible to detect the (valid?) newlines between the list items and not have them? 

Seems if you put the `.PP` *before* the `.IP` things work correctly.

**Comment by cpuguy83** [comment]
I think likely this is dependent on the markdown processor (https://github.com/russross/blackfriday) handing down.

Can you post the roff you expect to see?

**Comment by miekg** [comment]
Thanks, let me add so more detail,
this:
~~~ markdown
# blaat

## Name

blaat

* aaa

  * b
  * c
  * d
  * e

* bbbb
~~~
generates
~~~ nroff
.TH blaat
.SH Name
.PP
blaat

.RS
.IP \(bu 2

.PP
aaa
.RS
.IP \(bu 2
b
.IP \(bu 2
c
.IP \(bu 2
d
.IP \(bu 2
e

.RE
.IP \(bu 2

.PP
bbbb

.RE
~~~
because of the `.PP` *after* the `.IP`, this renders as
~~~ txt
 * 
 aaa
~~~~
etc

**Comment by cpuguy83** [comment]
I don't think having the extra newline between your nested list and the outer list is expected and blackfriday is *probably* (but I'm only guessing and haven't dug in) not treating it as a nested list.

**Comment by miekg** [comment]
well, I've happen to have written a markdown parser based on a blackfriday fork (don't ask), and that prints this ast:
~~~
% ./mmark -ast README.md 
Heading
  Text 'blaat'
Heading
  Text 'Name'
Paragraph
  Text 'blaat'
List 'flags=start'
  ListItem 'flags=has_block start'
    Paragraph
      Text 'aaa'
    List 'tight flags=start'
      ListItem 'flags=start'
        Paragraph
          Text 'b'
      ListItem
        Paragraph
          Text 'c'
      ListItem
        Paragraph
          Text 'd'
      ListItem
        Paragraph
          Text 'e'
  ListItem 'flags=has_block'
    Paragraph
      Text 'bbbb'
~~~
which parses this in a way I intended it. Of course this being markdown and blackfriday (v1) doesn't have this option; I'll have to double check

**Comment by miekg** [comment]
Ah, yes blackfriday is insert paragraphs:
~~~
% blackfriday-tool README.md
<h1>blaat</h1>

<h2>Name</h2>

<p>blaat</p>

<ul>
<li><p>aaa</p>

<ul>
<li>b</li>
<li>c</li>
<li>d</li>
<li>e</li>
</ul></li>

<li><p>bbbb</p></li>
</ul>
~~~
*sigh*

**Comment by miekg** [comment]
I think the valid thing here is to ignore paragraphs while in lists, unless the list contain a block level element. I'm doing something similar here: https://github.com/mmarkdown/mmark/blob/master/render/xml/renderer.go#L221

**Comment by cpuguy83** [comment]
This sounds reasonable.
Should this be optional?

**Comment by miekg** [comment]
Think this makes sense to do this always. You do need to insert a .pp if
there is a second paragraph in the listitem though

**Comment by cpuguy83** [comment]
Found the problem here. We just need to not write `.PP` when the parent is a header type.

**Comment by cpuguy83** [comment]
Well, that doesn't quite work because prev always seems to be a heading.

**Comment by cpuguy83** [comment]
But it seems, at least in your case above, node.Next is a list and we can skip the paragraph if we are in a list. Interestingly we already had a special case if the list depth was greater 0, but seems like we just don't want PP in a list at all.

**Comment by miekg** [comment]
my hack for this is here: https://github.com/mmarkdown/mmark/blob/master/render/man/renderer.go#L134
(using mmark now to convert to coredns README.mds into manual pages)

**Comment by cpuguy83** [comment]
I'm not sure where we fixed this, but this appears to be resolved now.
Taking your example now get this output:


```roff
.nh
.TH blaat
.SH Name
.PP
blaat

.RS
.IP \(bu 2
aaa
.RS
.IP \(bu 2
b
.IP \(bu 2
c
.IP \(bu 2
d
.IP \(bu 2
e

.RE

.IP \(bu 2
bbbb

.RE
```

**Comment by cpuguy83** [comment]
Closing this tentatively sense this seems OK now.
