### ISSUE TITLE
glide install error 

### ISSUE THREAD

**Issue by herohenu** [cpuguy83/go-md2man#53]
glide install it depend   go-md2man ,and shows : 
```shell
Error scanning github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "." in:
        /Users/xxxx/.glide/cache/src/https-github.com-cpuguy83-go-md2man/v2/md2man
```
it seems  need go mod , I update go to  go1.13 ,it still  install err ,what can I do can avoid "github.com/cpuguy83/go-md2man/v2/md2man"  import error ? thanks

**Comment by cpuguy83** [comment]
Unless glide supports modules, the import path will not work.
I suggest you use the v1.0.10 release in that case.

**Comment by herohenu** [comment]
> Unless glide supports modules, the import path will not work.
> I suggest you use the v1.0.10 release in that case.

find the real reason ,use `glide tree ` show all dependence ,and  it's the package use go-md2man
```yaml
package: github.com/stretchr/testify
-  version: ^1.2.2
+  version: 1.2.2
```
and it update to latest version,so I fixed it version not update and the question dissapear; 
thank u the same.

**Comment by djensen47** [comment]
It turns out that we may not have the choice to downgrade. I use a library that uses this as a dependency. For reasons, I'm still on go 1.11 and using glide. 

Unfortunately this is the reality of the world and it's affects people. I would hope you would reconsider this Issue.

**Comment by cpuguy83** [comment]
You can't downgrade to the 1.x tree?

In any case I don't plan to make changes to support glide on the v2 module.

**Comment by djensen47** [comment]
Actually, yes, I think that's fair. It's the fault of whatever library upgraded the dependency to a breaking version. You did the right thing, version 2 is modules and version 1 isn't.
