### ISSUE TITLE
Add v2 tag

### ISSUE THREAD

**Issue by soulgalore** [cpuguy83/go-md2man#54]
Hi,
I use go-md2man indirectly when building [WebPageReplay](https://github.com/catapult-project/catapult/tree/master/web_page_replay_go). I have problem with building that now since I get a _cannot find package_ for go-md2man from urfave/cli/. I'm no go-user so I'm not 100% how everything should work, but they say this project misses a v2 tag, adding that would solve the dependency issue see https://github.com/urfave/cli/issues/888#issuecomment-530807547

Would be ok for you to add that?

Best
Peter

**Comment by cpuguy83** [comment]
v2 tag was added last week.
