### ISSUE TITLE
missing implementation on Renderer

### ISSUE THREAD

**Issue by bilfash** [cpuguy83/go-md2man#55]
vendor/github.com/cpuguy83/go-md2man/md2man/roff.go:19:9: cannot use &roffRenderer literal (type *roffRenderer) as type blackfriday.Renderer in return argument:
        *roffRenderer does not implement blackfriday.Renderer (missing RenderFooter method)

**Comment by cpuguy83** [comment]
Thanks for reporting.

It looks like you are trying to use blackfriday v1.x with go-md2man v2 (which is what's on master and the latest tag).
go-md2man v2 requires blackfriday v2.
