### ISSUE TITLE
Build issues. 

### ISSUE THREAD

**Issue by mjknoxie** [cpuguy83/go-md2man#67]
comply uses go-md2man, the go-md2man fails to build. 

`==> make brew
Last 15 lines from /Users/michael.knox/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/trivago/tgo v1.0.7
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1`

Consistent on macOS 10.15, Intel and macOS 11 on M1

**Comment by cpuguy83** [comment]
Your go.sum is wrong.
It tells you what to do at the end of the error.

**Comment by mjknoxie** [comment]
not my go.sum :) I will update the bug with the comply project.

**Comment by jakesyl** [comment]
Having the same issue with a fresh go.sum post `go mod tidy`: https://github.com/xplorfin/go-template/pull/3/checks?check_run_id=2087276793 on go 1.16
