### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by williamh** [cpuguy83/go-md2man#70]
Hi Brian

This is just a friendly ping to find out the status of the project.
There hasn't been a release since 2019 and the last commit was in December 2020.

Can you please write back on this issue and give a status update?

Thanks,

William

**Comment by zimbatm** [comment]
Same. I would like to use the tilde fix that was merged in https://github.com/cpuguy83/go-md2man/pull/56 but no release has been done since.

**Comment by cpuguy83** [comment]
@williamh There is no need to release without changes, so in general things are pretty static and stable.

@zimbatm 
There's a couple of pending changes I'm looking for others to review just as a sanity check and we can cut a new release.
That said, no need to wait for a release to do a build.
