### ISSUE TITLE
new groff incompatibilities?

### ISSUE THREAD

**Issue by sten0** [cpuguy83/go-md2man#99]
Hi,

I'm a user of the Debian package (2.0.2+ds1-1), and lintian recently started forwarding these groff warnings:

groff-message an.tmac:<standard input>:508: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined) 

groff-message troff:<standard input>:113: warning: cannot select font 'C'

I'm guessing there was some sort of change in groff that go-md2man  now needs to adapt to.

'hope it's an easy fix!

**Comment by paravoid** [comment]
I reported this in the Debian specifically for the go-md2man package, as bug [#1049968](https://bugs.debian.org/1049968), and Cc'ed G. Branden Robinson (groff upstream, among other affiliations), who gave a very long and elaborate response, including specific recommendations for the go-md2man code. You may want to look into it and perhaps talk to him before implementing any fixes here.

**Comment by g-branden-robinson** [comment]
Can I be of any assistance?

**Comment by thaJeztah** [comment]
Contributions are welcome for sure 😅  (looks like I missed the original report, and just now saw this ticket). Also /cc @cpuguy83

**Comment by debarshiray** [comment]
> Contributions are welcome for sure 😅 (looks like I missed the original report, and just now saw this ticket). Also /cc @cpuguy83

I put something together in https://github.com/cpuguy83/go-md2man/pull/105 based on the conversation between @paravoid and @g-branden-robinson on the Debian [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1049968).  I checked the HTML and PS outputs with `man -Thtml ...` and `man -Tps`  respectively.

**Comment by paravoid** [comment]
Thanks for working on this! I just tested go-md2man 2.0.3 with crun's manpage and:

> > groff-message an.tmac::508: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined)
> 
> This actually results in malformed output, tables not rendered. Thankfully the fix is easy, as described here: add `'\" t` as the very first line of the output: See https://lists.debian.org/debian-devel/2023/08/msg00220.html

This is **not** fixed.

> > groff-message troff::113: warning: cannot select font 'C'

This _is_ fixed.

**Comment by debarshiray** [comment]
> > > groff-message an.tmac::508: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined)
> > 
> > This actually results in malformed output, tables not rendered. Thankfully the fix is easy, as described here: add `'\" t` as the very first line of the output: See https://lists.debian.org/debian-devel/2023/08/msg00220.html
> 
> This is **not** fixed.

Yes, sorry, my bad.  I should have been more explicit.

Part of the problem is that I am unable to reproduce the `tbl preprocessor failed` warning with `crun(1)`.  I tried with crun 1.9.2, which was built with GNU roff 1.23, on Fedora 39.

I could try to come up with a fix if you gave me some more explicit hints on how to reproduce.

> > groff-message troff::113: warning: cannot select font 'C'
>
> This is fixed.

I couldn't reproduce this one easily, either, but it was failing my test suite, which was doing something similar to `man toolbox | head` or `man toolbox | grep ...` and running into the warnings.

**Comment by paravoid** [comment]
> > > > groff-message an.tmac::508: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined)
> > > 
> > > 
> > > This actually results in malformed output, tables not rendered. Thankfully the fix is easy, as described here: add `'\" t` as the very first line of the output: See https://lists.debian.org/debian-devel/2023/08/msg00220.html
> > 
> > 
> > This is **not** fixed.
> 
> Yes, sorry, my bad. I should have been more explicit.
> 
> Part of the problem is that I am unable to reproduce the `tbl preprocessor failed` warning with `crun(1)`. I tried with crun 1.9.2, which was built with GNU roff 1.23, on Fedora 39.
> 
> I could try to come up with a fix if you gave me some more explicit hints on how to reproduce.

On a fresh Debian sid system, e.g. by running `podman run --rm -it debian:sid`:
```
$ 
root@1fd0128f4302:/# apt update
root@1fd0128f4302:/# apt install -y go-md2man man-db wget
root@1fd0128f4302:/# wget https://raw.githubusercontent.com/containers/crun/main/crun.1.md
root@1fd0128f4302:/# go-md2man -in crun.1.md -out crun.1
root@1fd0128f4302:/# LC_ALL=C.UTF-8 MANROFFSEQ='' MANWIDTH=80 man --warnings -E UTF-8 -l -Tutf8 -Z crun.1 >/dev/null
an.tmac:<standard input>:844: warning: tbl preprocessor failed, or it or soelim was not run; table(s) likely not rendered (TE macro called with TW register undefined)
```

**Comment by thaJeztah** [comment]
Let me reopen this issue at least if there's things left to fix (for visibility)

**Comment by paravoid** [comment]
Any news here? Thanks :)

**Comment by cpuguy83** [comment]
@paravoid Something like this? https://github.com/cpuguy83/go-md2man/pull/111
